export enum ErrorCodeValues {
    USER_NOT_LOGGED = 'USER_NOT_LOGGED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_PASSWORD_MISMATCH = 'USER_PASSWORD_MISMATCH',
    USER_OK = 'USER_OK',
    USER_RIGHTS_NOT_ENOUGH = 'USER_RIGHTS_NOT_ENOUGH',
}